apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cmdb-lite.fullname" . }}-backend
  labels:
    {{- include "cmdb-lite.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cmdb-lite.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cmdb-lite.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cmdb-lite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.server.port }}
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env.environment }}
            - name: SERVER_PORT
              value: "{{ .Values.env.server.port }}"
            - name: DATABASE_HOST
              value: {{ .Values.env.database.host | default (printf "%s-postgresql" (include "cmdb-lite.fullname" .)) }}
            - name: DATABASE_PORT
              value: "{{ .Values.env.database.port }}"
            - name: DATABASE_NAME
              value: {{ .Values.env.database.name }}
            - name: DATABASE_USER
              value: {{ .Values.env.database.user }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cmdb-lite.fullname" . }}-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "cmdb-lite.fullname" . }}-secrets
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}