apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cmdb-lite.fullname" . }}-frontend
  labels:
    {{- include "cmdb-lite.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cmdb-lite.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cmdb-lite.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cmdb-lite.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: VITE_API_URL
              value: "http://{{ include "cmdb-lite.fullname" . }}-backend:{{ .Values.backend.service.port }}"
            - name: VITE_ENVIRONMENT
              value: {{ .Values.env.environment }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}